### ISSUE TITLE
backend: endpoint de users /auth/user

### ISSUE THREAD

**Issue by paoloose** [medicomas/documed-backend-express#12]
Esta tarea depende de la autenticación y autorización (#6)

GET `/auth/users`

GET `/auth/users/{id}`

Si el token es válido:

```json
HTTP 200 OK
{
	"email": "damaris@medicomas.com",
	"names": "Dr. Damaris Marian",
	"surnames": "Del Carpio Martinez",
	"roles": ["ADMIN", "DOCTOR"]
}
```

Otherwise ->

```json
HTTP 401 Not Authorized
```

**Comment by damarizz** [comment]
looks VERY good to me
(:

**Comment by paoloose** [comment]
closed thanks to https://github.com/medicomas/documed-backend-express/commit/83bf50a3e0dffb0a663b665c6a0f9b59c60e3719 🎉
